### PR TITLE
Install make, nano, sqlite into ~/.swc/opt instead of ~/.swc/lib

### PR DESCRIPTION
**Pull request by embray**
Seems somewhat more appropriate.  I don't know if there was any specific reason to choose lib/

### CODE REVIEW

**Comment by wking** [comment]
On Mon, Jun 13, 2016 at 11:30:24AM -0700, Erik Bray wrote:
> Seems somewhat more appropriate.  I don't know if there was any
> specific reason to choose lib/

I didn't record a reason behind ‘lib’ in 806fedff.  It's hard to pick
a good name when the executable and shared libraries are all unpacked
into the same directory, but I didn't care enough to split them apart
;).

‘lib’ → ‘opt’ works for me, but can you make a new PR for that against
the ‘python’ branch?  This one is against ‘master’.

**Comment by embray** [comment]
Sure.  I think /opt is best for questions of "this software is not installed in a unix-like manner!"

**Comment by embray** [comment]
Although I *have* seen lib/ used for that before too.  But it gives me a bad feeling.

**Comment by embray** [comment]
I'm going to go ahead and merge this into master since I don't see why it shouldn't be consistent.  But I will hand-merge into the python branch as well.

**Pull request merged**
