### PR TITLE
Prevent checkbox that runs main install script from being unchecked

### LINKED ISSUE #28: If you uncheck that last box, nano won't be in your PATH
We had a couple of students using Windows who had used the SWC windows installer but didn't have nano in their `PATH`.

It seems that they went through the installer but maybe **unchecked** that last box, "Launch Software Carpentry Windows Installer".

swc_installer_1

It seems innocuous, but then the installer halts without adding the necessary lines to `~/.bash_profile` to update the `PATH` variable.

Maybe change the text that goes with that check box to something that would discourage unchecking?

### PR DESCRIPTION
**Pull request by ethanwhite**
Fixes #28

### CODE REVIEW

**Comment by ethanwhite** [comment]
There is an option to hide the checkbox entirely, but I thought that might prove more confusing since something will run (visibly) after clicking `Finish`.

**Comment by wking** [comment]
I have no Windows machine to test it on, but this approach looks
reasonable to me.

**Comment by ethanwhite** [comment]
@kbroman - if this sounds like it will solve your issue in #28 I'll go ahead and get it merged.

**Comment by kbroman** [comment]
This, looks great, thanks!

**Comment by ethanwhite** [comment]
Thanks for reporting this @kbroman. I'll get it on the To Do list to roll another release so that we can get this rolled out for upcoming workshops.

**Pull request merged**
