### PR TITLE
Fix typo in nose entrypoint script

### PR DESCRIPTION
**Pull request by embray**
This can't have been right....?

### CODE REVIEW

**Comment by wking** [comment]
On Mon, Jun 13, 2016 at 11:22:34AM -0700, Erik Bray wrote:
> This can't have been right....?

Heh.  I think this is a sign that we aren't using nose much anymore
;).  Can you create a new PR targetting the ‘python’ branch (you'll
probably have to cherry-pick your commit over to avoid pulling in
‘master’ stuff)?  I can setup the python-targetting PR if you like.

**Comment by embray** [comment]
I can do that, but what is the purpose of the 'python' branch as opposed to master (which also has Python stuff)

**Comment by wking** [comment]
On Mon, Jun 13, 2016 at 01:00:12PM -0700, Erik Bray wrote:
> I can do that, but what is the purpose of the 'python' branch as
> opposed to master (which also has Python stuff)

There's some background in #1.

**Comment by embray** [comment]
I looked at #1 and still have no idea what the need is for these separate branches or what "namespaced" refers to.

**Comment by embray** [comment]
Likewise I'm going to go ahead and merge this then cherry-pick into the python branch.

**Pull request merged**
